# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c55ba3cc830160f3a6c3f80addb26f35b34eb62903489053959c90b8f5bfdfdf003b70b0127a0d49d60c44decaf4f7890cbdf73caf7a7762f74cc32e24ce8f8

test:
  secret_key_base: ec51bf73e5b1413be6f2d458d9b2c8caa0e643b656b79c33ca37e04c4ba0ccee10591e9ed2fcf47794a86137703452fd5849d64f8ef15bd58922afc78aeb5246

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
